:bug: make ide happy
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop pull request #73
Opened 2024-03-05 07:47 UTC by AzideCupric

但是小刻自己不开心了

2024-03-06 16:45 UTC, phidiaLam approved these changes

2024-03-07 07:37 UTC, phidiaLam approved these changes

2024-03-07 07:37 UTC, phidiaLam commented on src/view/home/TimeLine.vue
> +        :key="`${cookie.source.type}:${cookie.source.data}:${cookie.item?.id}`"
60行还有个:id，顺手了呗

2024-03-08 11:20 UTC, Goodjooy requested changes

2024-03-08 11:20 UTC, Goodjooy commented on src/api/operations/newestTimeline.ts
> +    await emit("need-timeline");
这部分是一对的，下面标记类型void，上面用string？

2024-03-08 11:20 UTC, Goodjooy commented on src/api/operations/operate.ts
> +            let window = getAll().find((window: WebviewWindow) => window.label == "notification",) ?? null;
这里直接！可以吗？这个窗口一定在的

2024-03-08 12:17 UTC, AzideCupric commented on src/api/operations/newestTimeline.ts
> +    await emit("need-timeline");
emit没有泛型

2024-03-08 12:29 UTC, Goodjooy commented on src/api/operations/newestTimeline.ts
> +    await emit("need-timeline");
那emit的是undfined，listen那边用闭包入参是string？

2024-03-08 12:33 UTC, AzideCupric commented on src/api/operations/newestTimeline.ts
> +    await emit("need-timeline");
```ts
declare function emit(event: string, payload?: unknown): Promise<void>;
```
这是 event.d.ts 给 emit 标注的类型

2024-03-08 12:50 UTC, Goodjooy commented on src/api/operations/newestTimeline.ts
> +    await emit("need-timeline");
没影响啊 listen那边泛型也不应该是string啊

2024-03-08 13:13 UTC, Goodjooy approved these changes

2024-03-08 13:28 UTC, merged