✨ 支持计算缓存目录大小和清理超期缓存
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop pull request #82
Opened 2024-09-03 16:16 UTC by AzideCupric

在设置页面

顺便修改了初始窗口大小到 1280x720

2024-09-05 02:14 UTC, Goodjooy requested changes
在Tauri中，除了提供command功能，还提供了[Event](https://tauri.app/v1/guides/features/events) 来推送消息，也许这边的实现中的缓存统计、清理缓存过程、清理完成等可以通过event来由Rust 部分主动推送？
此外，也许也能通过一个独立的携程来专门处理cache清理的相关任务，利用消息队列来推送清理相关请求，可以避免使用互斥锁。这样command部分只需要推送cache任务即可

2024-09-05 02:14 UTC, Goodjooy commented on src-tauri/src/commands/cache.rs
> +        let modified = metadata.modified().unwrap();
这里应该使用的是AccessTime 吧？将近3个月没有访问的文件夹删除？

2024-09-05 02:14 UTC, Goodjooy commented on src-tauri/src/commands/cache.rs
> +    }
这里只遍历一层会不会容易删除不完整？增加一层便利深度也许更好？

2024-09-05 02:14 UTC, Goodjooy commented on src/components/SettingPage.vue
> +          </v-btn>
这边需要搞个清理中的进度条吗？
https://vuetifyjs.com/en/components/progress-circular/

2024-09-05 02:23 UTC, Goodjooy commented
对了，文件操作要用异步吗？https://docs.rs/tokio/latest/tokio/fs/struct.ReadDir.html

2024-09-05 02:47 UTC, AzideCupric commented
这得引入tokio依赖了吧

2024-09-05 02:48 UTC, Goodjooy commented
> 这得引入tokio依赖了吧

tokio 不是 tauri 本来就在依赖里面吗？

2024-09-05 03:58 UTC, AzideCupric commented
> 在Tauri中，除了提供command功能，还提供了[Event](https://tauri.app/v1/guides/features/events) 来推送消息，也许这边的实现中的缓存统计、清理缓存过程、清理完成等可以通过event来由Rust 部分主动推送？
> 此外，也许也能通过一个独立的携程来专门处理cache清理的相关任务，利用消息队列来推送清理相关请求，可以避免使用互斥锁。这样command部分只需要推送cache任务即可

感觉需要实现两个要求
- 同时只有一个清理命令执行
- 短时间重复的清理命令是没有意义的，过多的请求应该被忽略

2024-09-05 07:20 UTC, Goodjooy commented
> > 在Tauri中，除了提供command功能，还提供了[Event](https://tauri.app/v1/guides/features/events) 来推送消息，也许这边的实现中的缓存统计、清理缓存过程、清理完成等可以通过event来由Rust 部分主动推送？
> > 此外，也许也能通过一个独立的携程来专门处理cache清理的相关任务，利用消息队列来推送清理相关请求，可以避免使用互斥锁。这样command部分只需要推送cache任务即可
> 
> 感觉需要实现两个要求
> 
>     * 同时只有一个清理命令执行
> 
>     * 短时间重复的清理命令是没有意义的，过多的请求应该被忽略

那也许Event更好？
单独的携程处理cache文件。处理完成后一段时间内接收请求但是不处理
idle  -占用请求 -> 计算cache -> 计算完毕后推送cache 占用Event -> idle
idel -> 清理cache 请求 -> 推送"清理中"Event,清理cache -> 推送“清理完成” Event -> 等待一段时间，这段时间接收请求但不执行 -> idle 

这样就能保证同时只有一个清理在运行

2025-02-07 15:53 UTC, AzideCupric commented on src-tauri/src/commands/cache.rs
> +        let modified = metadata.modified().unwrap();
AccessTime可能会被系统禁止更新吧

2025-02-07 15:54 UTC, AzideCupric commented on src-tauri/src/commands/cache.rs
> +    }
直接删目录的话，不存在删除不完整吧

2025-02-07 15:57 UTC, AzideCupric commented on src/components/SettingPage.vue
> +          </v-btn>
一般删的都会很快，感觉看不到就结束了，已经有loading参数了，意思一下就好吧

2025-02-08 03:14 UTC, Goodjooy approved these changes

2025-02-08 03:14 UTC, Goodjooy commented on src-tauri/src/commands/cache.rs
> +        if now.duration_since(modified).unwrap() > Duration::from_secs(60 * 60 * 24 * 3) {
这块unwrap是什么情况
https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.modified
https://doc.rust-lang.org/std/time/struct.SystemTime.html#method.duration_since

要不要考虑处理一下，以免全崩？

2025-02-09 00:59 UTC, merged